---
version: 2
updates:
  # We use PDK, so don't auto-update Ruby dependencies
  # - package-ecosystem: 'bundler'
  #   directory: '/'
  #   schedule:
  #     # Check for updates to Ruby gems every week
  #     interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
