---
appveyor.yml:
  delete: true
.devcontainer/devcontainer.json:
  unmanaged: true
.gitignore:
  required:
    - '/.librarian'
    - '/.tmp'
    - '/spec/fixtures/work-dir'
    - 'rspec.xml'
.gitlab-ci.yml:
  delete: true
.rspec:
  unmanaged: true
Rakefile:
  changelog_project: 'puppet-qualys_agent'
  changelog_user: 'broadinstitute'
  changelog_version_tag_pattern: '%s'
  extra_disabled_lint_checks:
    - '80chars'
    - 'autoloader_layout'
    - 'puppet_url_without_modules'
  requires:
    - 'puppet-lint/tasks/puppet-lint'
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
.travis.yml:
  delete: true
.yardopts:
  delete: true
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  coverage_report: true
  hiera_config: 'spec/fixtures/hiera.yaml'
  mock_with: ':rspec'
