---
appveyor.yml:
  delete: true
.gitignore:
  required:
    - '/.librarian'
    - '/.tmp'
    - '/spec/fixtures/work-dir'
.gitlab-ci.yml:
  delete: true
Rakefile:
  changelog_project: 'puppet-qualys_agent'
  changelog_user: 'broadinstitute'
  changelog_version_tag_pattern: '%s'
  extra_disabled_lint_checks:
    - '80chars'
    - 'autoloader_layout'
    - 'puppet_url_without_modules'
  requires:
    - 'puppet-lint/tasks/puppet-lint'
Gemfile:
  optional:
    ':development':
      - gem: 'dpl'
      - gem: 'dpl-puppet_forge'
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
.travis.yml:
  delete: true
.yardopts:
  delete: true
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera.yaml'
