---
appveyor.yml:
  delete: true
.gitignore:
  required:
    - '/.librarian'
    - '/.tmp'
    - '/spec/fixtures/work-dir'
.gitlab-ci.yml:
  delete: true
Rakefile:
  extra_disabled_lint_checks:
    - '80chars'
    - 'autoloader_layout'
    - 'puppet_url_without_modules'
  requires:
    - 'puppet-lint/tasks/puppet-lint'
Gemfile:
  optional:
    ':development':
      - gem: 'dpl'
      - gem: 'dpl-puppet_forge'
.travis.yml:
  delete: true
.yardopts:
  delete: true
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  hiera_config: 'spec/fixtures/hiera.yaml'
