---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: broadinstitute/puppet-qualys_agent
  description:
    Puppet module for installing and configuring the Qualys Cloud Agent
  name: puppet-qualys_agent
  tags:
    - bits
    - bits-tools
    - puppet
    - qualys
  title: puppet-qualys_agent
spec:
  lifecycle: production
  owner: bits-aviso
  system: puppet
  type: service
