---
name: 'test_deploy'

'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test_deploy:

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v4'

      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1.156.0'
        env:
          BUNDLE_SILENCE_ROOT_WARNING: '1'
          BUNDLE_WITH: 'development'
        with:
          bundler-cache: true
          ruby-version: '3.2'
          rubygems: 'latest'

      - name: 'Module build'
        run: 'bundle exec pdk build --force'

      - name: 'Test module install'
        run: 'bundle exec puppet module install pkg/broadinstitute-qualys_agent-*.tar.gz'
